### ISSUE TITLE
[R7RS 5.3.1] A top-level redefinition of apply or call-with-values is ignored by any procedure body compiled before it ran

### ISSUE THREAD

**Issue by baijum** [kaappi/kaappi#2457]
**Kaappi version**

`aeaa82a6` (post-#2452) **and** `5cdfc118` (pre-#2452). Verified A/B against two
binaries built from those two commits: identical output. Pre-existing, not a
regression from #2452 — filing it because that PR's review surfaced it.

**Platform**

macOS aarch64, ReleaseSafe

**Description**

#2033 fixed the case where a top-level redefinition of `apply` / `eval` /
`call/cc` / `call-with-values` runs **before** the code that uses the name. The
reverse order is still wrong: a procedure body compiled before the redefinition
executes keeps the builtin forever, in both tail and non-tail position.

`globalBindingStillGenuine` (`src/compiler.zig`) decides the fast path by
reading the live global environment at **compile** time. R7RS §5.3.1 makes a
top-level definition "essentially the same effect as the assignment
expression", so the binding a call resolves is a run-time question; deciding it
when the enclosing body happens to be compiled gets the answer wrong whenever
the two orders differ.

This is not a general property of the compiler's compile-time gates. `car` and
`map` in the identical shape do honour the later redefinition — only the names
#2033 covers bake in.

**Minimal reproduction**

```scheme
(import (scheme base) (scheme write))

;; Each body is compiled BEFORE the redefinitions below execute.
(define (nt-apply) (let ((v (apply + (list 1 2)))) v))          ; non-tail
(define (t-apply)  (apply + (list 1 2)))                        ; tail
(define (nt-cwv)   (let ((v (call-with-values (lambda () 1) (lambda (x) x)))) v))
(define (t-cwv)    (call-with-values (lambda () 1) (lambda (x) x)))
(define (nt-car)   (let ((v (car (list 1 2)))) v))              ; contrast
(define (nt-map)   (let ((v (map (lambda (x) x) (list 1 2)))) v))

(define (apply f xs) 'user-apply)
(define (call-with-values p c) 'user-cwv)
(define (car xs) 'user-car)
(define (map f xs) 'user-map)

(write (list (nt-apply) (t-apply) (nt-cwv) (t-cwv) (nt-car) (nt-map)))
```

| form | expected (R7RS 5.3.1) | Kaappi |
|---|---|---|
| `(nt-apply)` | `user-apply` | `3` |
| `(t-apply)` | `user-apply` | `3` |
| `(nt-cwv)` | `user-cwv` | `1` |
| `(t-cwv)` | `user-cwv` | `1` |
| `(nt-car)` | `user-car` | `user-car` ✓ |
| `(nt-map)` | `user-map` | `user-map` ✓ |

**Full output**

```text
(3 3 1 1 user-car user-map)
```

Swapping the declaration order — redefinitions first — gives `user-apply` /
`user-cwv` for all four, which is #2033's fixed case.

**Does it panic or raise a Scheme error?**

Neither: it silently runs the builtin and discards the user's procedure.

**Note on `#2452`'s scope**

#2452 gave non-tail `apply` / `call-with-values` their own opcodes, so the
*mechanism* on that path changed (`call_global` → the `apply` opcode at top
level; inside a procedure body it was already baking in the builtin). The
*observable* behaviour above did not — both binaries print the same line. Two
things worth recording for whoever picks this up:

- At top level the pre-#2452 non-tail path emitted a real by-name
  `call_global`, and the post-#2452 path emits the `apply` opcode. That
  difference is unobservable, because a top-level form runs once and cannot be
  re-entered after a later definition — but it means the top-level disassembly
  is misleading about which path a procedure body takes.
- Inside a procedure body the pre-#2452 non-tail path already baked in the
  builtin, which is why the A/B is clean. I have not pinned down which
  compile-time decision did that pre-#2452; whoever fixes this should establish
  it rather than assume the #2033 gate was the only one.

**Suggested resolution**

The honest fix is to make the decision a run-time one for these names, the way
`car`/`map` already are: keep the superinstruction but guard it, or fall back to
a by-name call once any top-level definition of the name has been seen. A
cheaper interim is to extend the conservative arm — `globalBindingStillGenuine`
already declines on a `set!` target anywhere in the enclosing form — to decline
when the name is *defined* anywhere in the compilation unit, not just assigned.
That costs the fast path in programs that shadow these names at all, which is
the right trade: they are the programs whose semantics we are currently getting
wrong.

Whatever the fix, it should cover all five #2033 names, not just the two
#2452 touched.

**Priority rationale**

`priority: medium` per `docs/dev/github-issues.md`: wrong against a spec, and
silently — which aggravates within the level rather than promoting it. Not
`high`: reaching it needs a program that redefines one of five specific
`(scheme base)` names at top level *after* the code that calls them, which is
rare and already unusual enough that #2033 was itself filed as medium.
