### PR TITLE
apply/call-with-values: resumable cwv producer (#2453) and unit-wide gate decline for redefined names (#2457)

### LINKED ISSUE #2453: call-with-values' producer is still driven by a native frame, and a continuation captured there reports the wrong error
**Kaappi version**

HEAD with #2452 applied (also reproduces identically on `8b0f3504`, before it).

**Platform**

macOS aarch64, ReleaseSafe

**Description**

#2451 moved `call-with-values`' **consumer** into the bytecode dispatch loop, in
both tail and non-tail position. Its **producer** did not move: it still runs
under `%call-with-values->list`'s own native frame (`vm.callThunk`), exactly as
it ran under `callWithValuesFn`'s before.

So a continuation captured inside the producer still cannot be resumed after the
form returns. That is a leftover of the same conformance gap #2451 closed for the
consumer — R7RS-small requires `call/cc` to produce fully re-entrant
continuations, and `call-with-values` is a core procedure.

Worse than the restriction itself is how it reports. The diagnostic is not the
honest `KP3000` the restriction has everywhere else — it is an `apply` type error
blaming an argument the user never wrote:

```text
error[KP3002]: apply: last argument must be a list
```

That comes from the `tail_apply`/`apply` that follows the producer call: the
resumed continuation delivers into the register that was holding the produced
value list, and the apply then reads a non-list out of it. A reader has no route
from that message to the actual cause.

**Minimal reproduction**

```scheme
(import (scheme base) (scheme write))

(let ((saved #f) (n 0))
  (define (p) (call/cc (lambda (k) (set! saved k))) (set! n (+ n 1)) 1)
  (define (g) (call-with-values p (lambda (x) x)))   ; producer captures
  (g)
  (if (< n 3) (saved 'again) (display "ok")))
```

**Full output**

```text
error[KP3002]: apply: last argument must be a list
```

Expected either `ok` (the conformant outcome) or, failing that, the accurate
`KP3000: continuation cannot resume across a returned native call`.

Non-tail position behaves the same way; this is not a tail-vs-non-tail
asymmetry, which is why #2451 scoped it out rather than folding it in.

**Does it panic or raise a Scheme error?**

Raises. No panic, no silent wrong answer — but the message misidentifies the
problem, which is what makes it worth more than a docs note.

**Suggested resolution**

Two parts, separable and in this order:

1. **Diagnostic** — the misdirection is the cheap half and stands on its own. A
   resume that lands past a returned `%call-with-values->list` should report
   `KP3000` like every other returned-native-call resume, not let the following
   `apply` blame its operand.
2. **Engine** — lower the producer the way #2451 lowered the consumer: call it
   with an ordinary `call` opcode so its frame lives in the copied VM state,
   then spread the produced values into the consumer's arguments. The obstacle
   is diagnostic parity, not mechanism: `%call-with-values->list` exists
   precisely to keep `callWithValuesFn`'s two type checks (both operands,
   producer-first, before the producer runs) and its exact `typeError` texts, so
   splitting it means keeping those checks somewhere the compiled sequence can
   still reach before it calls anything.

`README.md` "Known limitations → Continuations" already names this corner as of
#2452; it can be dropped from there when this lands.

**Priority rationale**

`priority: medium` per `docs/dev/github-issues.md`: behaviour is wrong against a
spec (R7RS-small first-class continuations), but it is loud — an error, no hang,
no data loss. The inaccurate message is an aggravator within the level, not a
level of its own; it does not reach `high`, since nothing silently returns a
wrong answer. Consistent with #2451 and #2060, both medium.

### LINKED ISSUE #2457: [R7RS 5.3.1] A top-level redefinition of apply or call-with-values is ignored by any procedure body compiled before it ran
**Kaappi version**

`aeaa82a6` (post-#2452) **and** `5cdfc118` (pre-#2452). Verified A/B against two
binaries built from those two commits: identical output. Pre-existing, not a
regression from #2452 — filing it because that PR's review surfaced it.

**Platform**

macOS aarch64, ReleaseSafe

**Description**

#2033 fixed the case where a top-level redefinition of `apply` / `eval` /
`call/cc` / `call-with-values` runs **before** the code that uses the name. The
reverse order is still wrong: a procedure body compiled before the redefinition
executes keeps the builtin forever, in both tail and non-tail position.

`globalBindingStillGenuine` (`src/compiler.zig`) decides the fast path by
reading the live global environment at **compile** time. R7RS §5.3.1 makes a
top-level definition "essentially the same effect as the assignment
expression", so the binding a call resolves is a run-time question; deciding it
when the enclosing body happens to be compiled gets the answer wrong whenever
the two orders differ.

This is not a general property of the compiler's compile-time gates. `car` and
`map` in the identical shape do honour the later redefinition — only the names
#2033 covers bake in.

**Minimal reproduction**

```scheme
(import (scheme base) (scheme write))

;; Each body is compiled BEFORE the redefinitions below execute.
(define (nt-apply) (let ((v (apply + (list 1 2)))) v))          ; non-tail
(define (t-apply)  (apply + (list 1 2)))                        ; tail
(define (nt-cwv)   (let ((v (call-with-values (lambda () 1) (lambda (x) x)))) v))
(define (t-cwv)    (call-with-values (lambda () 1) (lambda (x) x)))
(define (nt-car)   (let ((v (car (list 1 2)))) v))              ; contrast
(define (nt-map)   (let ((v (map (lambda (x) x) (list 1 2)))) v))

(define (apply f xs) 'user-apply)
(define (call-with-values p c) 'user-cwv)
(define (car xs) 'user-car)
(define (map f xs) 'user-map)

(write (list (nt-apply) (t-apply) (nt-cwv) (t-cwv) (nt-car) (nt-map)))
```

| form | expected (R7RS 5.3.1) | Kaappi |
|---|---|---|
| `(nt-apply)` | `user-apply` | `3` |
| `(t-apply)` | `user-apply` | `3` |
| `(nt-cwv)` | `user-cwv` | `1` |
| `(t-cwv)` | `user-cwv` | `1` |
| `(nt-car)` | `user-car` | `user-car` ✓ |
| `(nt-map)` | `user-map` | `user-map` ✓ |

**Full output**

```text
(3 3 1 1 user-car user-map)
```

Swapping the declaration order — redefinitions first — gives `user-apply` /
`user-cwv` for all four, which is #2033's fixed case.

**Does it panic or raise a Scheme error?**

Neither: it silently runs the builtin and discards the user's procedure.

**Note on `#2452`'s scope**

#2452 gave non-tail `apply` / `call-with-values` their own opcodes, so the
*mechanism* on that path changed (`call_global` → the `apply` opcode at top
level; inside a procedure body it was already baking in the builtin). The
*observable* behaviour above did not — both binaries print the same line. Two
things worth recording for whoever picks this up:

- At top level the pre-#2452 non-tail path emitted a real by-name
  `call_global`, and the post-#2452 path emits the `apply` opcode. That
  difference is unobservable, because a top-level form runs once and cannot be
  re-entered after a later definition — but it means the top-level disassembly
  is misleading about which path a procedure body takes.
- Inside a procedure body the pre-#2452 non-tail path already baked in the
  builtin, which is why the A/B is clean. I have not pinned down which
  compile-time decision did that pre-#2452; whoever fixes this should establish
  it rather than assume the #2033 gate was the only one.

**Suggested resolution**

The honest fix is to make the decision a run-time one for these names, the way
`car`/`map` already are: keep the superinstruction but guard it, or fall back to
a by-name call once any top-level definition of the name has been seen. A
cheaper interim is to extend the conservative arm — `globalBindingStillGenuine`
already declines on a `set!` target anywhere in the enclosing form — to decline
when the name is *defined* anywhere in the compilation unit, not just assigned.
That costs the fast path in programs that shadow these names at all, which is
the right trade: they are the programs whose semantics we are currently getting
wrong.

Whatever the fix, it should cover all five #2033 names, not just the two
#2452 touched.

**Priority rationale**

`priority: medium` per `docs/dev/github-issues.md`: wrong against a spec, and
silently — which aggravates within the level rather than promoting it. Not
`high`: reaching it needs a program that redefines one of five specific
`(scheme base)` names at top level *after* the code that calls them, which is
rare and already unusual enough that #2033 was itself filed as medium.

### PR DESCRIPTION
**Pull request by baijum**
## What

One PR for both issues because they edit the same lowering seam: #2453 rewrites the emission `compiler_passthrough.compileCallWithValuesForm` produces, and #2457 changes the compile-time gate (`globalBindingStillGenuine`) that decides whether that emission (and its four sibling fast paths) is used at all.

Closes #2457
Closes #2453

Three commits, matching #2453's own "separable and in this order":

1. **KP3000 diagnostic (#2453 part 1).** A continuation captured in `call-with-values`' producer, resumed after the form returned, misfired as `error[KP3002]: apply: last argument must be a list` — the producer's frame was pushed by `callThunk` with `returns_to_native = false`, so its late return fell through the dispatch loop's `raiseDeadNativeReturn` check and delivered into a stale register the following apply then misread. New `callThunkReturningToNative` marks the frame (the same marker `callWithArgs`-driven natives already use), so every route that still drives the producer natively raises the honest, catchable KP3000 instead. The repro goes KP3002 → KP3000.
2. **The lowering (#2453 part 2).** The producer is now called with an ordinary `call` opcode — its frame is a VM frame in the caller's bytecode, copied by capture and restored by resume — then a new `values_list` opcode (appended last in the enum per the `.sbc` numbering constraint; count gate and the four quoting docs updated to 33) spreads the produced value(s) into the argument list the existing `apply`/`tail_apply` consumes. A resume re-runs the spread and the consumer with the newly produced values. Diagnostic parity is kept by a new `%call-with-values-check` primitive called first: both operands type-checked producer-first, before anything runs, with `callWithValuesFn`'s exact texts. `%call-with-values->list` is deleted (nothing emits it). The repro now prints `ok` — the conformant outcome, in both positions.
3. **The gate (#2457, the issue's interim option).** Established first, per the issue's caveat: the #2033 gate is the *only* interpreter-tier decision that bakes the five names in — its decline path resolves by name at run time (`isContinuationBarrier` routes these names away from `call_global` toward the same by-name `get_global` + `call`, and neither constant folder folds them), and pre-#2452 the same gate decided the in-body non-tail path, which is why the issue's A/B was clean. The native tier has a second, independent gate: `emitApplyForm`'s `rebound_globals`/`native_fns` are populated in emission order, so it had the same use-before-define hole for the one name it lowers structurally. The interim: drivers with whole-unit knowledge (file runs cold and `.sbc`-HIT replay, stdin scripts, `kaappi compile`'s `.sbc` pass, `kaappi check` — and the native backend, whose `compileNative` installs the scan and whose `emitApplyForm` consults it) pre-scan the unit's top-level `define`/`define-values`/`set!` targets through `begin`/`cond-expand` splices, and the gate declines for those names everywhere in the unit. The run-time-decision redesign stays the recorded follow-up; the REPL, `eval`, and macro-materialized redefinitions deliberately keep the legacy compile-time answer. Every spine the scan walks is a guarded `SpineWalk` (a cyclic `(begin . #0=(1 . #0#))` must reach the run loop's KP2001 diagnosis, not spin in the pre-scan).

## Tests

- `tests/scheme/continuations/callcc-cwv-native-kp3000-2453.scm` — native-route producer resume reports KP3000, tail and non-tail (the guard encloses the capture: a resume restores the capture-time handler stack).
- `tests/scheme/continuations/callcc-cwv-producer-reentry-2453.scm` — producer re-entry past the form's return in both positions, several/no values, a resume re-spreading newly produced values, ordinary semantics, and the three diagnostic shapes (bad consumer before the producer body runs, bad producer, both-bad producer-first, consumer arity).
- `tests/scheme/compliance/top-level-redefinition-order-2457.scm` — all five #2033 names, tail and non-tail, use-compiled-before-define plus the define-first control, later `set!`, `begin`-spliced redefinition, non-procedure redefinition, `car`/`map` contrast.
- `tests/scheme/compile/native-apply-redefinition-order-2457.sh` — the compiled binary agrees with the interpreter for both orders, and a clean program keeps its native `@kaappi_apply` site with zero eval fallbacks (#1803's convergence guarantee).
- Zig: a collector unit test (all define shapes, splices, define-values formals, and non-captures).

Three existing tests moved, each because a unit-wide define of these names now declines the superinstruction for the whole file, which would conflate what they pin with the gate's resolution rules: the begin-sibling-define pair from `callcc-native-driver-reentry-2451.scm` to `top-level-redefinition-2033.scm`, and the two `tail_call_cc` receiver-arity pins from the `primitives_control` audit to `callcc-correctness.scm`. README's Known limitations drops the producer corner (#2452 had named it).

## Evidence

- `zig build test`: 1990/2011 pass, 21 skip, 0 fail; under `-Dgc-stress=true`: 1995/2011, 16 skip, 0 fail.
- `bash tests/scheme/run-all.sh`: **2140 pass, 0 fail** (745 Scheme files + the 1395-test R7RS suite), including `native-apply-lowering-1803.sh` and `native-apply-lexical-scope-1799.sh`.
- Both issue repros verified against the final build, on cold runs and `.sbc` cache-HIT replays: #2457 prints `(user-apply user-apply user-cwv user-cwv user-car user-map)`, #2453 prints `ok`.

🤖 Generated with [Claude Code](https://claude.com/claude-code)

### CODE REVIEW

File: src/compiler_gate.zig [hunk 1]
```diff
@@ -0,0 +1,377 @@
...
+    // unit (kaappi#2457): a body compiled before the definition runs
+    // would otherwise bake the builtin in and silently discard the user's
+    // procedure, because this function's compile-time read of the global
+    // environment still sees the pristine binding. Whole-unit drivers
+    // populate the set; per-form entry points (REPL, eval) leave it null
+    // and keep the legacy answer. Declining only ever costs the
+    // superinstruction — the by-name call resolves the genuine binding
+    // when no redefinition intervenes.
+    if (passthrough.unit_top_level_targets) |unit_targets| {
+        if (unit_targets.contains(sym_name) or unit_targets.contains(base_name)) return false;
```
[the remark this answers is not in the document]
Comment (baijum) [reply src/compiler_gate.zig:62]: Verified on the PR head. The finding reproduces only for the **use-site-name** shape:

```scheme
(define (nt) (let ((v (apply + (list 1 2)))) v))
(define-syntax redef (syntax-rules () ((_ n) (set! n (lambda (f xs) 'macro-set)))))
(redef apply)
(write (list (nt) (apply + '(1 2))))   ; => (3 macro-set)
```

A template-introduced `(define (apply f xs) ...)` is not a redefinition here at all — hygiene renames it, so top-level `apply` is untouched and the same program prints `(3 3)` on `main` and on this branch alike.

Declining for this PR, with the reasoning:

- The output is byte-identical on `main` before this PR. The whole-unit scan only *narrowed* a pre-existing hole; it did not introduce this one.
- The PR description, the `collectUnitTopLevelTargets` doc comment, and the `top-level-redefinition-order-2457.scm` header all record macro-materialized redefinitions as outside the interim — alongside `eval` and the REPL, and (verified) `load`, which a macro-aware scan would not fix either.
- Making the scan macro-aware means speculatively expanding every top-level form of every file — the cost #1775 had to cap with a budget for the *per-form* scan — for a corner that the run-time decision #2457 asked for retires wholesale, together with the other three routes.

Tracked as #2469, which lists all four residual routes with repros and the run-time design.

**Comment by baijum** [comment]
LGTM.

**Verified locally on `746c5f4d`** (macOS aarch64, ReleaseSafe):

- `zig build test --summary all`: 1993/2014 pass, 21 skip, 0 fail — matches the PR's numbers.
- The two new continuation files, the new `top-level-redefinition-order-2457.scm`, and the four files that had tests moved (`top-level-redefinition-2033`, `callcc-native-driver-reentry-2451`, `callcc-correctness`, `primitives_control-audit`) all pass under an isolated `KAAPPI_HOME`.
- Both issue repros: #2457 prints `(user-apply user-apply user-cwv user-cwv user-car user-map)` on a cold run, on the `.sbc` cache HIT, and via stdin; #2453 prints `ok`. `kaappi check` is clean on both the define-later and `set!`-later shapes.
- Read through the lowering: `check_base` is `base+1`, so `values_list check_base, producer_reg` lands the list exactly where `apply base, 1` reads it, and `consumer_reg` is freed before the producer's `call` so the callee's frame grows above the live registers. The `values_list` arm roots `v` across `buildRestList`/`allocPair` and the `defer popRoot` is strictly nested. `callThunkReturningToNative` passes the same `returns_to_native = true` that `callWithArgs`-driven callbacks get. The `.sbc` cache is keyed by compiler hash (version + build id), so the appended opcode needs no format bump — same as #2452's `apply`.

**The benchmark comment's 🔴 `list` 1.31x is CI noise.** Neither `list.scm` nor `string.scm` touches `apply` or `call-with-values`, and `list` has sat within ±3% on the last five merged PRs. Local A/B of a `main` build against this head, best of 5, same machine:

| benchmark | main | PR | ratio |
|---|---:|---:|---:|
| `list` | 190.1 ms | 185.4 ms | 0.98x |
| `string` | 47.1 ms | 45.4 ms | 0.96x |
| `hashtable` | 197.1 ms | 191.6 ms | 0.97x |

**One thing to add before merging: a `CHANGELOG.md` `[Unreleased]` entry.** Every PR merged since #2452 carries one (#2455, #2461, #2462, #2463, #2465), and this one adds an opcode, retires `%call-with-values->list`, and closes two conformance issues — exactly what the release skill reconstructs from `git log` when it is missing. Or apply `no-changelog` if that is deliberate.

**CodeRabbit's open thread** (macro-materialized redefinitions) — declined in a reply with the reasoning: it reproduces only for the use-site-name `set!` shape, is byte-identical on `main`, and is already documented as outside the interim. Filed **#2469** for the run-time-gate redesign, listing every residual route with repros: `load` and `eval` (both still print `3` for the #2457 shape on this head), the REPL, macro-materialized `set!`, and the WASM playground entry (`kaappi_step_setup` has the whole source but installs no set — three lines to add to the interim if you want it now).

Non-blocking: a file that `load`s another compiles the inner file under the outer file's target set, which can only decline more fast paths — correct, just worth knowing when reading `unit_top_level_targets`.
